In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time
from scipy.stats import linregress
from pprint import pprint
import json
import collections

In [3]:
pop_data = "Resources\population_data.csv"
pop_data_df = pd.read_csv(pop_data)
pop_data_df.head(25)

,State,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,California,37320903,37641823,37960782,38280824,38625139,38953142,39209127,39399349,39557045,39747267,39937489
1,Texas,25242679,25646227,26089620,26489464,26977142,27486814,27937492,28322717,28701845,29087070,29472295
2,Florida,18845785,19093352,19326230,19563166,19860330,20224249,20629982,20976812,21299325,21646155,21992985
3,New York,19400080,19498514,19574549,19628043,19656330,19661411,19641589,19590719,19542209,19491339,19440469
4,Pennsylvania,12711158,12744583,12766827,12776621,12789101,12785759,12783538,12790447,12807060,12813969,12820878
5,Illinois,12840762,12867291,12884119,12898269,12888962,12864342,12826895,12786196,12741080,12700381,12659682
6,Ohio,11539327,11543463,11548369,11576576,11602973,11617850,11635003,11664129,11689442,11718568,11747694
7,Georgia,9711810,9801578,9901496,9973326,10069001,10181111,10304763,10413055,10519475,10627767,10736059
8,Wyoming,564483,567224,576270,582123,582548,585668,584290,578934,577737,572381,567025
9,Vermont,625880,626979,626063,626212,625218,625197,623644,624525,626299,627180,628061
10,Alaska,713906,722038,730399,737045,736307,737547,741504,739786,737438,735720,734002
11,North Dakota,674710,685136,701116,721999,737382,754022,754353,755176,760077,760900,761723
12,South Dakota,816165,823484,833496,842270,849088,853933,862890,873286,882235,892631,903027
13,Delaware,28704,19870,9170,5385,3645,2470,1482,1005,700,540,185

In [5]:
for state in pop_data_df["State"]:
    x_axis = pop_data_df.columns.tolist()
    y_axis = pop_data_df.loc[pop_data_df["State"]== state][2,:]
    plt.plot(x_axis, y_axis)
    plt.show()

TypeError: '(2, slice(None, None, None))' is an invalid key